%Problem 5 - Part A - HW 5
%MAT 226B
%Carter Johnson

% To test your program, use n × n matrices A generated by
% A = make_3d_laplacian(m).
% Note that n = m3 and that the exact eigenvalues ? = ?i,j,` of A are given by
% Lambda i,j,l = 2( 3 - cos i pi/(m + 1) - cos j pi/(m+1) - cos l pi/(m+1) )
%   for i,j,l = 1, 2, ..., m

%Test your program on the 8 × 8 matrix A corresponding to m = 2 and the starting
% vector r provided in the Matlab file ?HW5_P5a.mat?. Run the algorithm for
% kmax = 4 steps and compute the eigenvalues of T4 with Matlab?s ?eig? command.
% Compare these eigenvalues with the exact eigenvalues of A.

m=2;
A = make_3d_laplacian(m);
load('HW5_P5a.mat')
kmax = 4;

T = hermitian_lanczos(A,r,kmax);
[V,D] = eig(T);

%make analytic eigenvalues
lambda = @(ii,jj,ll) 2.*( 3 - cos((ii.*pi)./(m + 1)) -cos((jj.*pi)./(m + 1)) - cos((ll.*pi)./(m + 1)) );
k=1;
lambdas = zeros(m^3,1);
for ii=1:m
    for jj=1:m
        for ll=1:m
            lambdas(k) = lambda(ii,jj,ll);
            k = k+1;
        end
    end
end
