%Problem 5 - Part B - HW 5
%MAT 226B
%Carter Johnson

% To test your program, use n × n matrices A generated by
% A = make_3d_laplacian(m).
% Note that n = m3 and that the exact eigenvalues ? = ?i,j,` of A are given by
% Lambda i,j,l = 2( 3 - cos i pi/(m + 1) - cos j pi/(m+1) - cos l pi/(m+1) )
%   for i,j,l = 1, 2, ..., m
% 
% Employ your program to obtain approximate eigenvalues of the 328509 × 328509
% matrix A corresponding to m = 69, using the starting vector r provided in the
% Matlab file ?HW5_P5b.mat?. Compute the approximate eigenvalues obtained from
% the Lanczos matrices Tk for
% k = 250, 500, 1000, 2000.
% For each of these values of k, print out the 10 smallest and the 10 largest eigenvalues
% of Tk and compare them with the 10 smallest and the 10 largest exact
% eigenvalues of A. 

m=69;
A = make_3d_laplacian(m);
load('HW5_P5b.mat')

kmax = [250; 500; 1000; 2000;];
for k = 1:size(kmax,1)
   T = hermitian_lanczos(A,r,kmax(k));
   [V,D] = eig(T); 
   sorted_lambdas = sort(diag(D));
   display(kmax(k));
   min_lambdas = sorted_lambdas(1:10);
   max_lambdas = sorted_lambdas(end:-1:end-9);
   table(min_lambdas, max_lambdas)
end

%make analytic eigenvalues
lambda = @(ii,jj,ll) 2.*( 3 - cos((ii.*pi)./(m + 1)) -cos((jj.*pi)./(m + 1)) - cos((ll.*pi)./(m + 1)) );
% [ii,jj,ll] = meshgrid(1:m, 1:m, 1:m);
% lambdas = lambda(ii,jj,ll);
k=1;
lambdas = zeros(m^3,1);
for ii=1:m
    for jj=1:m
        for ll=1:m
            lambdas(k) = lambda(ii,jj,ll);
            k = k+1;
        end
    end
end
sorted_lambdas = sort(lambdas);
min_lambdas = sorted_lambdas(1:10);
max_lambdas = sorted_lambdas(end:-1:end-9);
display('exact lambdas');
table(min_lambdas, max_lambdas)

